name: Craft
main: TheFixDev\Craft\Main
version: 1.0.0
api: 4.0.0
author: TheFixDev

commands:
  craft:
    description: Open the workbench
    permission: craft.use

permissions:
  craft.use:
    default: op
    description: you can use the craft command
