name: Craft
main: TheFixDev\Craft\Main
version: 1.0.0
api: 4.0.0
author: TheFixDev

commands:
  craft:
    description: Open the workbench
    permission: workbench.use
    default: op
permissions:
  workbench.use: 
   default: op
